import { Booking, BookingStatus } from '../domain/entities/Booking';
import { BookingRepository, RoomRepository, GuestRepository } from '../domain/repositories/Interfaces';
import { CreateBookingDTO } from './DTOs';

export class BookingUseCase {
    constructor(
        private bookingRepo: BookingRepository,
        private roomRepo: RoomRepository,
        private guestRepo: GuestRepository
    ) { }

    async execute(dto: CreateBookingDTO): Promise<Booking> {
        const guest = await this.guestRepo.findById(dto.guestId);
        if (!guest) {
            throw new Error('Guest not found');
        }

        const room = await this.roomRepo.findById(dto.roomId);
        if (!room) {
            throw new Error('Room not found');
        }

        // Convert string dates to Date objects
        const checkIn = new Date(dto.checkInDate);
        const checkOut = new Date(dto.checkOutDate);

        // Basic validation
        if (checkIn >= checkOut) {
            throw new Error('Check-in date must be before check-out date');
        }

        // Check availability
        const availableRooms = await this.roomRepo.findAvailable(checkIn, checkOut);
        const isAvailable = availableRooms.some(r => r.id === room.id);

        if (!isAvailable) {
            throw new Error('Room is not available for the selected dates');
        }

        // Create Booking
        const booking = new Booking(
            0, // ID will be generated by Repo
            guest,
            room,
            checkIn,
            checkOut,
            BookingStatus.PENDING
        );

        return await this.bookingRepo.save(booking);
    }
}
